// Clase que usa el paquete de Firebase para configurar las opciones de Firebase.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0gcb1WLsIjxCDvzRH3_Mgmx6DVYTbqgs',
    appId: '1:500397475151:web:87bda20ea6485e8e5cf13a',
    messagingSenderId: '500397475151',
    projectId: 'warranty-acf47',
    authDomain: 'warranty-acf47.firebaseapp.com',
    storageBucket: 'warranty-acf47.appspot.com',
    measurementId: 'G-KSLG9QHWQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKDb_KpjxXlFadPRVa5lljKX-cXv4iWxw',
    appId: '1:500397475151:android:67da30e7a2fa5c875cf13a',
    messagingSenderId: '500397475151',
    projectId: 'warranty-acf47',
    storageBucket: 'warranty-acf47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOm4Irft-m5qsd9_ky8BghNgaYY24Eec',
    appId: '1:500397475151:ios:4b29b2e0f0a098195cf13a',
    messagingSenderId: '500397475151',
    projectId: 'warranty-acf47',
    storageBucket: 'warranty-acf47.appspot.com',
    iosBundleId: 'com.example.warrantyAutoManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXOm4Irft-m5qsd9_ky8BghNgaYY24Eec',
    appId: '1:500397475151:ios:4b29b2e0f0a098195cf13a',
    messagingSenderId: '500397475151',
    projectId: 'warranty-acf47',
    storageBucket: 'warranty-acf47.appspot.com',
    iosBundleId: 'com.example.warrantyAutoManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0gcb1WLsIjxCDvzRH3_Mgmx6DVYTbqgs',
    appId: '1:500397475151:web:0fd6db64b43fc3e95cf13a',
    messagingSenderId: '500397475151',
    projectId: 'warranty-acf47',
    authDomain: 'warranty-acf47.firebaseapp.com',
    storageBucket: 'warranty-acf47.appspot.com',
    measurementId: 'G-4R24KDFK1Q',
  );
}
